#ifndef ENUM_H_INCLUDED
#define ENUM_H_INCLUDED
enum _COLOR_PAIRS {
    CP_TILE_DIRT=1,CP_TILE_AIR,CP_TILE_STONE,CP_TILE_GRASS,CP_PLAYER,CP_TILE_OAK_LEAF,CP_TILE_OAK_TRUNK
};
enum _TILE_IDS {
    TILE_AIR=0,TILE_DIRT,TILE_STONE,TILE_GRASS
};
#endif